trigger:
- main

pool:
  name: 'my_mac_os'

steps:
- script: |
    docker build -t my-c-app .
  displayName: 'Build Base Docker img'

- script: |
    docker run --name my-app-running my-c-app
  displayName: 'Run the docker container'
  continueOnError: true

- script: |
    docker rm my-app-running
  displayName: "Kill running app container"

- script: |
    docker rmi my-c-app
  displayName: "Remove the image from docker"
